const languages = {
    zh: {
        title: "Pizza 配送数据统计",
        delivery_count: "总配送次数",
        pizza_count: "总披萨数量",
        avg_time: "平均配送时间（分钟）",
        total_sales: "总销售额（美元）",
        feedback_count: "总反馈数",
        high_quality: "高质量反馈",
        medium_quality: "中质量反馈",
        low_quality: "低质量反馈",
        area: "配送区域",
        all: "全部",
        boston: "波士顿",
        cambridge: "剑桥",
        somerville: "萨默维尔",
        order_type: "订单类型",
        web: "网络",
        phone: "电话",
        chart_title: "配送数量随时间变化",
        chart_hint: "鼠标悬停查看详情"
    },
    en: {
        title: "Pizza Delivery Dashboard",
        delivery_count: "Total Deliveries",
        pizza_count: "Total Pizzas",
        avg_time: "Average Delivery Time (mins)",
        total_sales: "Total Sales (USD)",
        feedback_count: "Total Feedback",
        high_quality: "High Quality",
        medium_quality: "Medium Quality",
        low_quality: "Low Quality",
        area: "Delivery Area",
        all: "All",
        boston: "Boston",
        cambridge: "Cambridge",
        somerville: "Somerville",
        order_type: "Order Type",
        web: "Web",
        phone: "Phone",
        chart_title: "Deliveries VS Time",
        chart_hint: "Hover for details"
    }
};